#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/IdentityMessageService.cshtml")]
    public partial class _Views_Emails_IdentityMessageService_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Emails_IdentityMessageService_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("To: ");

            
            #line 1 "..\..\Views\Emails\IdentityMessageService.cshtml"
Write(ViewBag.To);

            
            #line default
            #line hidden
WriteLiteral("\r\nFrom: ");

            
            #line 2 "..\..\Views\Emails\IdentityMessageService.cshtml"
 Write(ViewBag.From);

            
            #line default
            #line hidden
WriteLiteral("\r\nSubject: ");

            
            #line 3 "..\..\Views\Emails\IdentityMessageService.cshtml"
    Write(ViewBag.Subject);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title></title>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Emails\IdentityMessageService.cshtml"
Write(ViewBag.Body);

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
