// <auto-generated />
namespace KDCLLC.Identity.Services.Data.Migrations.PrimaryKeyString
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class GroupRoleInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupRoleInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201502031146490_GroupRoleInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
